import Head from 'next/head';

import About from '@/features/About';
import Hero from '@/features/Hero';
import MenuHighlights from '@/features/MenuHighlights';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main>
        <About />
        <MenuHighlights />
      </main>
    </>
  );
}
